"""Initial migration

Revision ID: 115aba74dd6b
Revises: 
Create Date: 2025-05-11 13:34:43.066629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115aba74dd6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('overall_performance', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('motivations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('RESOURCE', 'TEST', name='documentcategory'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('awareness_level', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.Float(), nullable=True),
    sa.Column('performance_level', sa.Float(), nullable=True),
    sa.Column('satisfaction_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_deadline', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_session_resource',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'document_id')
    )
    op.create_table('learning_session_test',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'document_id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('evaluation', sa.Float(), nullable=True),
    sa.Column('test_document_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_session.id'], ),
    sa.ForeignKeyConstraint(['test_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('learning_session_test')
    op.drop_table('learning_session_resource')
    op.drop_table('milestone')
    op.drop_table('learning_session')
    op.drop_table('document')
    op.drop_table('project')
    # ### end Alembic commands ###
