"""Update Question model relationships

Revision ID: 2358406e0877
Revises: 49b19c617e0c
Create Date: 2025-05-15 21:17:17.873099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2358406e0877'
down_revision = '49b19c617e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_resource',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'document_id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    op.drop_table('question_resource')
    # ### end Alembic commands ###
