"""Add source_type field to Question model

Revision ID: 2825db1a9aa8
Revises: 0f449872a150
Create Date: 2025-06-10 23:12:43.468614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Enum


# revision identifiers, used by Alembic.
revision = '2825db1a9aa8'
down_revision = '0f449872a150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # First add the column with a default value
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type',
                                       sa.Enum('RESOURCE', 'TEST', name='questionsourcetype'),
                                       server_default='RESOURCE',  # Set default value for existing records
                                       nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    # Drop the enum type
    sa.Enum(name='questionsourcetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###